// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLABujn4O_RWG3ssomMbtgCzCSgCaqXeI',
    appId: '1:329383398566:web:06cd3d15e800b6435e3867',
    messagingSenderId: '329383398566',
    projectId: 'arzan-a8f6d',
    authDomain: 'arzan-a8f6d.firebaseapp.com',
    storageBucket: 'arzan-a8f6d.firebasestorage.app',
    measurementId: 'G-2YRL5X2X2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9SVmMHn4aPuB96VPsFwmKiAtOtRnwts8',
    appId: '1:329383398566:android:1c0e45cd380bfe685e3867',
    messagingSenderId: '329383398566',
    projectId: 'arzan-a8f6d',
    storageBucket: 'arzan-a8f6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgbdEGimXqPI3FD1bQvzaM2in1eWZZRKo',
    appId: '1:329383398566:ios:a5ac84ac192c86995e3867',
    messagingSenderId: '329383398566',
    projectId: 'arzan-a8f6d',
    storageBucket: 'arzan-a8f6d.firebasestorage.app',
    iosBundleId: 'com.example.arzan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgbdEGimXqPI3FD1bQvzaM2in1eWZZRKo',
    appId: '1:329383398566:ios:a5ac84ac192c86995e3867',
    messagingSenderId: '329383398566',
    projectId: 'arzan-a8f6d',
    storageBucket: 'arzan-a8f6d.firebasestorage.app',
    iosBundleId: 'com.example.arzan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLABujn4O_RWG3ssomMbtgCzCSgCaqXeI',
    appId: '1:329383398566:web:acdf768bfe6832ee5e3867',
    messagingSenderId: '329383398566',
    projectId: 'arzan-a8f6d',
    authDomain: 'arzan-a8f6d.firebaseapp.com',
    storageBucket: 'arzan-a8f6d.firebasestorage.app',
    measurementId: 'G-NJ305D3QN6',
  );
}
