import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/app_colors.dart';
import '../../domain/entities/promo_code.dart';
import '../../domain/usecases/create_promo_code.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../providers/promo_code_provider.dart';

class PostPage extends ConsumerStatefulWidget {
  const PostPage({super.key});

  @override
  ConsumerState<PostPage> createState() => _PostPageState();
}

class _PostPageState extends ConsumerState<PostPage> {
  final _formKey = GlobalKey<FormState>();
  final _codeController = TextEditingController();
  final _serviceController = TextEditingController();
  final _commentController = TextEditingController();
  DateTime? _expirationDate;
  bool _isSubmitting = false;

  @override
  void dispose() {
    _codeController.dispose();
    _serviceController.dispose();
    _commentController.dispose();
    super.dispose();
  }

  Future<void> _selectExpirationDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now().add(const Duration(days: 30)),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null) {
      final time = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
      );
      if (time != null) {
        setState(() {
          _expirationDate = DateTime(
            picked.year,
            picked.month,
            picked.day,
            time.hour,
            time.minute,
          );
        });
      }
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final currentUser = ref.read(currentUserProvider);
    if (currentUser == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please sign in to post')),
      );
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    final promoCode = PromoCode(
      id: '', // Will be generated by repository
      code: _codeController.text.trim(),
      serviceName: _serviceController.text.trim(),
      authorId: currentUser.id,
      comment: _commentController.text.trim().isEmpty
          ? null
          : _commentController.text.trim(),
      publishDate: DateTime.now(),
      expirationDate: _expirationDate,
    );

    final useCase = ref.read(createPromoCodeProvider);
    final result = await useCase(promoCode);

    result.fold(
      (failure) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: ${failure.message ?? 'Failed to create promo code'}')),
        );
        setState(() {
          _isSubmitting = false;
        });
      },
      (created) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Promo code posted successfully!')),
        );
        ref.read(promoCodesNotifierProvider.notifier).loadPromoCodes(refresh: true);
        Navigator.of(context).pop();
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Post Promo Code'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Service Name
              TextFormField(
                controller: _serviceController,
                decoration: const InputDecoration(
                  labelText: 'Service Name *',
                  hintText: 'e.g., Dodo Pizza, Fix Price',
                  prefixIcon: Icon(Icons.store),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter service name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Promo Code
              TextFormField(
                controller: _codeController,
                decoration: const InputDecoration(
                  labelText: 'Promo Code *',
                  hintText: 'Enter the promo code',
                  prefixIcon: Icon(Icons.confirmation_number),
                ),
                textCapitalization: TextCapitalization.characters,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter promo code';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Comment
              TextFormField(
                controller: _commentController,
                decoration: const InputDecoration(
                  labelText: 'Comment (Optional)',
                  hintText: 'Add any additional information',
                  prefixIcon: Icon(Icons.comment),
                ),
                maxLines: 3,
              ),
              const SizedBox(height: 16),

              // Expiration Date
              InkWell(
                onTap: _selectExpirationDate,
                child: InputDecorator(
                  decoration: const InputDecoration(
                    labelText: 'Expiration Date (Optional)',
                    prefixIcon: Icon(Icons.calendar_today),
                  ),
                  child: Text(
                    _expirationDate == null
                        ? 'Select expiration date'
                        : '${_expirationDate!.day}/${_expirationDate!.month}/${_expirationDate!.year} ${_expirationDate!.hour}:${_expirationDate!.minute.toString().padLeft(2, '0')}',
                  ),
                ),
              ),
              if (_expirationDate != null)
                Padding(
                  padding: const EdgeInsets.only(top: 8),
                  child: TextButton.icon(
                    onPressed: () {
                      setState(() {
                        _expirationDate = null;
                      });
                    },
                    icon: const Icon(Icons.clear),
                    label: const Text('Clear expiration date'),
                  ),
                ),
              const SizedBox(height: 32),

              // Submit Button
              ElevatedButton(
                onPressed: _isSubmitting ? null : _submit,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
                child: _isSubmitting
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Post Promo Code'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
